### PR TITLE
benchmarks: implement full-decode benchmarks based on the current decoder tests.

### PR DESCRIPTION
**Pull request by matthiaskrgr**
````
cargo bench
````
````
[...]
     Running target/release/deps/decode-a00302758db4e3cc

running 2 tests
test bench_logo_full_decode    ... bench: 100,105,811 ns/iter (+/- 19,727,934)
test bench_seasnail_raw_pixels ... bench:   2,719,731 ns/iter (+/- 316,937)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured; 0 filtered out
````

### CODE REVIEW

**Comment by dgriffen** [comment]
Is the `bench_seasnail_raw_pixels` test just ment to measure the conversion speed of the internal pixel representation? Because calling `get_raw_pixels` doesn't do any actual decoding work.

**Comment by matthiaskrgr** [comment]
Mh yeah, I can remove that...

**Comment by dgriffen** [comment]
The bench looks good as-is, but it may be more effective to measure the performance of the sea snail image since it has a non-trivial maniac tree. The logo flif only has one node.

**Comment by matthiaskrgr** [comment]
The sea snail bench would take 7 minutes to run on my system, this is quite a lot. :/
Do you know if there is a way to reduce the number of iterations?

**Comment by dgriffen** [comment]
I do not, I'm not very familiar with the Rust benching APIs. If it takes that long i think we can keep using the logo image but I'll need to find a way to measure the MANIAC performance.

**Comment by matthiaskrgr** [comment]
I can try to make a small cutout of the seashell, convert it to flif16 and add it to the repo for benchmarking

**Comment by dgriffen** [comment]
That would work, realistically we just need anything with a non-trivial maniac tree. You will have to be quite aggressive with the flags you pass into `flif.exe` though. Right now I've only verified the YCoCg and Bounds transformations as working.

**Comment by matthiaskrgr** [comment]
Benching of the cutout takes 24 seconds here now :)
test bench_cutout_full_decode ... bench:  70,577,774 ns/iter (+/- 66,800,926)

**Comment by dgriffen** [comment]
Looks great! I'll go ahead and merge this. At some point it would be cool to compare the performance against the reference FLIF implementation, but I can't find any benchmarks.

**Comment by matthiaskrgr** [comment]
Hm, I tried comparing flif @ 0.2 tag / 024b039 with flif.rs but I could not decode the sea snail image.
CORRUPTION DETECTED: checksums don't match (computed: fb34712f v/s read: 6e52a81d)! (partial file?)

**Comment by matthiaskrgr** [comment]
Anyway there is a ton of images here: https://github.com/FLIF-hub/benchmarks

**Comment by dgriffen** [comment]
Corruption message is odd, I created that file using the official FLIF binary.

**Comment by matthiaskrgr** [comment]
Do you know which git commit of the flif-hub/flif repo the binary is based on? I remember some note that flif16 is based on 0.2 tag, however in the upstream repo, there is v0.2 and v0.2.2 tag and it is not clear to me which tag the binary refers to (I have been building from sources myself ever since).
This might be worth noting somewhere in the readme.md ("this repo implements the flif16 standard based on commit/tag foo of upstream repo <url>).

**Comment by dgriffen** [comment]
The binary I have reports 0.2.0. However I think that 0.2.0 is compatible with 0.2.2. In fact the only breaking change I am aware of since 0.2.0 was with animated images using the ColorBuckets transformation, and it sounds like the 0.2.0 implementation of that was actually buggy so therefore not following the spec.

**Pull request merged**
